.TH DRINFO 1 "June 2024" "Version 1.0.4" "User Commands"
.SH NAME
drinfo \- display information about drives and their storage usage
.SH SYNOPSIS
.B drinfo
.RI [ OPTION ]
.SH DESCRIPTION
.B drinfo
lists all detected local and network drives and Shows mount point, filesystem type, device path,
UUID, label, mount options, used, available and inodes + SMART status (only as root).

.SH OPTIONS
.TP
.BR -h , --help
Show help message and exit.
.TP
.BR -v , --version
Show program version and exit.

.SH AUTHOR
Lennart Martens <monkeynator78@gmail.com>

.SH LICENSE
MIT License

.SH SEE ALSO
.BR df (1),
.BR lsblk (8)
